ARG IMAGE
FROM $IMAGE

RUN apt-get update && apt-get install -y openssh-server
EXPOSE 22

RUN apt-get install -y sudo
RUN mkdir -p /run/sshd

# Create a group and user account for the SSH connection
COPY sshd_deamon.sh /sshd_deamon.sh
RUN ln -s /opt/conda/bin/python /usr/bin/python
RUN chmod 755 /sshd_deamon.sh
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

CMD ["/sshd_deamon.sh"]
ENTRYPOINT ["sh", "-c", "/sshd_deamon.sh"]
