version: "2.3"
services:
  mmdetection3d:
    shm_size: '20gb'
    runtime: 'nvidia'
    build: 
      context: .
      dockerfile: Dockerfile-dev
      args:
        IMAGE: supervisely/mmdetection3d:1.0.0
    ports:
      - "5555:22"
    volumes:
      - "./data:/data"
