version: "2.3"
services:
  mmdetection3d:
    shm_size: '20gb'
    runtime: 'nvidia'
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        IMAGE: mmdet3d_py38:1.0.0
    ports:
      - "5554:22"
    volumes:
      - "./data:/data"
